export const SETTINGS_LABELS = {
    providerHeading: 'AI provider',
    provider: 'Provider',
    providerDesc: 'Choose the backend used for image transcription',
    openAiOption: 'OpenAI-compatible',
    ollamaOption: 'Ollama',
    ollamaHeading: 'Ollama configuration',
    ollamaUrl: 'Server URL',
    ollamaUrlDesc: 'The URL of your Ollama server',
    model: 'Vision model',
    modelDesc: 'Select an installed Ollama vision model for transcription',
    noModelsFound: 'No models found. Start Ollama and test the connection.',
    testConnection: 'Test connection',
    testConnectionDesc: 'Verify that the Ollama server is reachable',
    testConnectionButton: 'Test',
    recommendedModels: 'Recommended models',
    recommendedModelsDesc:
        'Vision models known to work well for transcription. Click install to download.',
    installButton: 'Install',
    installingButton: 'Installing...',
    customModel: 'Install custom model',
    customModelDesc: 'Enter any Ollama model name to install it',
    customModelPlaceholder: 'e.g. llava:13b',
    openAiHeading: 'OpenAI-compatible configuration',
    openAiBaseUrl: 'API endpoint',
    openAiBaseUrlDesc: 'Base URL for an OpenAI-compatible API',
    openAiApiKey: 'API key',
    openAiApiKeyDesc: 'Bearer API key used to authenticate requests',
    openAiApiKeyPlaceholder: 'Paste your OpenAI-compatible API key',
    temperature: 'Temperature',
    temperatureDesc: 'Controls randomness (0 to 2)',
    topP: 'Top P',
    topPDesc: 'Nucleus sampling probability (0 to 1)',
    maxTokens: 'Max tokens',
    maxTokensDesc: 'Maximum completion tokens returned by the model',
    transcriptionHeading: 'Transcription settings',
    prompt: 'Transcription prompt',
    promptDesc: 'The prompt sent to the vision model along with each image',
    includeSubfolders: 'Include subfolders',
    includeSubfoldersDesc: 'When transcribing a folder, also process images in subfolders',
    overwriteExisting: 'Overwrite existing files',
    overwriteExistingDesc: 'Overwrite existing markdown files when re-transcribing images'
} as const
